### ISSUE TITLE
Problème « mod_recitcahiertraces-v2.2.0-beta » et « filter_recitcahiertraces-v2.1.0-beta » sur un site Moodle 4.1.1

### ISSUE THREAD

**Issue by Quentin-Ha** [SN-RECIT-formation-a-distance/.github#1]
Bonjour,

J’essaye d’installer les plugins « mod_recitcahiertraces-v2.2.0-beta » et « filter_recitcahiertraces-v2.1.0-beta » sur un site Moodle 4.1.1 de test. J’utilise les versions beta des [plugins pour Moodle 4.1](https://github.com/SN-RECIT-formation-a-distance/.github/wiki/Plugin-pack-for-Moodle-4.1-(Beta)). Lorsque j’essaie d’ajouter une activité « Cahier de traces v2 » à un cours et que je rentre dedans, j’obtiens l’erreur suivante :

_Exception : Class 'recitcommon\Utils' not found
Trace de la pile  
•	line 89 of /mod/recitcahiertraces/view.php: Error thrown
•	line 42 of /mod/recitcahiertraces/view.php: call to recitcahiertraces\MainView->display()_

Il semble manquer des dépendances au plugin pour fonctionner correctement. Est-il possible d’obtenir de l’aide pour installer ces plugins sur un Moodle 4.1 ?
Merci d’avance,

Quentin H

**Comment by gustavobazzo** [comment]
Bonjour Quentin-Ha,

Merci de votre message.

Effectivement, la version v2.2.0-beta avait un petit bogue concernant la classe recitcommon\Utils. La version [v2.2.1-beta](https://github.com/SN-RECIT-formation-a-distance/moodle-mod_recitcahiertraces/releases/tag/v2.2.0-beta) a réglé cela.

Cependant, nous vous encourageons à télécharger la dernière version pour Moodle 4:

- Module [v2.3.0-beta](https://github.com/SN-RECIT-formation-a-distance/moodle-mod_recitcahiertraces/releases/tag/v2.3.0-beta)
- Filtre [v2.1.0-beta](https://github.com/SN-RECIT-formation-a-distance/moodle-filter_recitcahiertraces/releases/tag/v2.1.0-beta)
